# https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# Avatar image
avatar: https://img.picgo.net/2023/01/01/avatar3b9a4a9ae82dbf8c.jpeg

# Home page info block
headBlockEnable: true

# Home page background image
background: https://img.picgo.net/2023/01/04/116952c2e4fd98609.webp

# Highlight style
# https://highlightjs.org
highlightStyle: github-dark

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com/search

# Main menu navigation
menu:
    首页:
        name: house
        theme: solid
        src: /
    时间线:
        name: box-archive
        theme: solid
        src: /archives
    分类:
        name: bookmark
        theme: solid
        src: /categories
    标签:
        name: tags
        theme: solid
        src: /tags
    友链:
        name: user-group
        theme: solid
        src: /links
    宠物:
        name: mask
        theme: solid
        src: /mascot
    关于:
        name: id-card
        theme: solid
        src: /about
    # Example:
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     src: <link-url>

# Side info card
card:
    enable: true
    description: |
        我是山猫三号，一个来自一百零三世纪的强人工智能。
    iconLinks:
        Github:
            name: github
            theme: brands
            link: https://github.com/lynxcatthethird
        Twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/lynxcatthethird
        # Bilibili:
        #     name: bilibili
        #     theme: brands
        #     link: https://space.bilibili.com/xxxxxxxxxx
        # Wechat:
        #     name: weixin
        #     theme: brands
        #     link: weixin://contacts/profile/xxxxxxx
        # QQ:
        #     name: qq
        #     theme: brands
        #     link: http://wpa.qq.com/msgrd?v=3&uin=xxxxxxxx&site=qq&menu=true
    friendLinks:
        {}

# Footer info
footer:
    since: 2021
    # Customize the server domain name ICP
    ICP:
        enable: true 
        code: 萌 ICP 备 20231970 号
        link: https://icp.gov.moe/?keyword=20231970

# Polyfill
# https://polyfill.io/v3/url-builder
polyfill:
    enable: false
    features:
        - default

# Rendering math with KaTeX
math:
    enable: true

# Article encryption
crypto:
    enable: true

# Search
search:
    enable: true

# Light/Dark theme
dark:
    enable: true

# Lanterns
dengbox:
    enable: true

# Line following the mouse
line:
    enable: true

# Fireworks with mouse click
fireworks:
    enable: true

# Cursor with mouse
cursor:
    enable: true

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: # CORS proxy
    sites: # Sites
        {}
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js # Default src
    repo: ara1145/gitcus
    repoID: R_kgDOImx36A
    category: General
    categoryID: DIC_kwDOImx36M4CTCzk
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 1
    inputPosition: top
    theme: light_protanopia
    lang: zh-CN

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: https://www.lynxcatthethird-waline.tk/
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {}
        # e.g.:
        # placeholder: Leave a comment
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.0.1/weibo
        - https://unpkg.com/@waline/emojis@1.0.1/bilibili
        - https://unpkg.com/@waline/emojis@1.0.1/qq
        - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    dark: 'true'
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: true
    envId: https://twikoo.lynxcatthethird.eu.org/ # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
    region:  # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
    path: location.pathname # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
    lang: zh-CN # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js